spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_sharing_service
    username: administrator
    password: admin
  flyway:
    enabled: true
    locations: classpath:db/migration